# The URL the site will be built for
base_url = "http://test.ai"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "hephaestus"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
bundled = "true"
author = "Jaxon Yue"
about = "Graduate Student at Duke University"

menu = [
{ text = "Home", link = "/" },
#{ text = "About", link = "/about/" },
{ text = "Education", link = "/education" },
#{ text = "Skills", link = "/skills/" },
{ text = "Projects", link = "/projects/"}
]


social = [
{ user = "Email Address", link = "mailto:jaxon.yue1@gmail.com", icon = "mail-outline"},
{ user = "GitLab", link = "https://gitlab.com/jaxonyue", icon = "gitlab"}
]